### ISSUE TITLE
Get-AudioFile throws error due to missing optional Apple components

### ISSUE THREAD

**Issue by awsr** [jherby2k/AudioWorks#24]
Running version 1.0.0-beta9 on up-to-date Windows 10 with PowerShell 7.0.2 and no Apple libraries installed.

Tested using OGG, MP3, and WAV files. All files gave the same error: _The type initializer for 'AudioWorks.Extensibility.ExtensionContainerBase' threw an exception._

Error record seems to point to:
[AudioWorks/AudioWorks/src/AudioWorks.Extensibility/ExtensionContainerBase.cs](https://github.com/jherby2k/AudioWorks/blob/b0fd4ff8b104b25cd332551f7f56f3440b71ed9f/AudioWorks/src/AudioWorks.Extensibility/ExtensionContainerBase.cs)
and
https://github.com/jherby2k/AudioWorks/blob/b0fd4ff8b104b25cd332551f7f56f3440b71ed9f/AudioWorks/src/Extensions/AudioWorks.Extensions.Apple/CoreAudioHandler.cs#L56-L71

Full error text follows:

```
Exception             :
    Type           : System.TypeInitializationException
    TypeName       : AudioWorks.Extensibility.ExtensionContainerBase
    TargetSite     : Void .ctor()
    StackTrace     :
   at AudioWorks.Extensibility.ExtensionContainerBase..ctor()
   at AudioWorks.Extensibility.ExtensionContainer`1..ctor()
   at AudioWorks.Extensibility.ExtensionContainer`1.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at AudioWorks.Extensibility.ExtensionContainer`1.get_Instance()
   at AudioWorks.Extensibility.ExtensionProvider.GetFactories[T](String key, String value)
   at AudioWorks.Api.ExtensionProviderWrapper.GetFactories[T](String key, String value)
   at AudioWorks.Api.AudioFile.LoadInfo()
   at AudioWorks.Api.AudioFile..ctor(String path)
   at AudioWorks.Api.TaggedAudioFile..ctor(String path)
   at AudioWorks.Commands.GetAudioFileCommand.ProcessPath(String path)
   at AudioWorks.Commands.GetAudioFileCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Message        : The type initializer for 'AudioWorks.Extensibility.ExtensionContainerBase' threw an exception.
    InnerException :
        Type       : System.IO.DirectoryNotFoundException
        TargetSite :
            Name          : CreateDirectoryHandle
            DeclaringType : System.IO.Enumeration.FileSystemEnumerator`1[TResult]
            MemberType    : Method
            Module        : System.IO.FileSystem.dll
        StackTrace :
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern)
   at AudioWorks.Extensibility.ExtensionLoadContext.<>c__DisplayClass3_0.<LoadUnmanagedDll>b__0(String path)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at AudioWorks.Extensibility.ExtensionLoadContext.LoadUnmanagedDll(String unmanagedDllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
   at System.Runtime.InteropServices.Marshal.PrelinkCore(MethodInfo m)
   at System.Runtime.InteropServices.Marshal.Prelink(MethodInfo m)
   at AudioWorks.Extensions.Apple.CoreAudioHandler.Handle() in d:\a\1\s\AudioWorks\src\Extensions\AudioWorks.Extensions.Apple\CoreAudioHandler.cs:line 60
   at AudioWorks.Extensibility.ExtensionContainerBase..cctor()
        Message    : Could not find a part of the path 'C:\Program Files\Common Files\Apple\Apple Application Support'.
        Source     : System.IO.FileSystem
        HResult    : -2147024893
    Source         : AudioWorks.Extensibility
    HResult        : -2146233036
CategoryInfo          : NotSpecified: (:) [Get-AudioFile], TypeInitializationException
FullyQualifiedErrorId : System.TypeInitializationException,AudioWorks.Commands.GetAudioFileCommand
InvocationInfo        :
    MyCommand        : Get-AudioFile
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 2
    Line             : Get-AudioFile .\gap100ms.wav
    PositionMessage  : At line:1 char:1
                       + Get-AudioFile .\gap100ms.wav
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-AudioFile
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

**Comment by jherby2k** [comment]
Oops! Thank you. Fixed - try the command again.

**Comment by awsr** [comment]
I can confirm that the updated version in the build artifact works without throwing an error.
